import type { NextPage } from 'next'
import Head from 'next/head'
import { Box } from 'components/Box'

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>learn.csesoc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Hello World!</p>
      </main>
    </Box>
  )
}

export default Home
